"""Aplica cambios editoriales localizados sobre las fuentes vigentes respaldadas."""
from pathlib import Path
import json

ROOT = Path(__file__).resolve().parents[1]
P = ROOT / 'Plantilla_ProyAplicado'
OUT = ROOT / 'reportes/revision_redaccion_integral_2026_10_05'
changes = []

def paragraph(name, start, new):
    path = P / name
    text = path.read_text(encoding='utf-8')
    candidates = [part for part in text.splitlines() if part.startswith(start)]
    if len(candidates) != 1:
        raise ValueError((name, start, len(candidates)))
    old = candidates[0].split('\n')[0]
    text = text.replace(old, new, 1)
    path.write_text(text, encoding='utf-8', newline='\n')
    changes.append({'archivo': name, 'antes': old, 'despues': new})

def phrase(name, old, new):
    path = P / name
    text = path.read_text(encoding='utf-8')
    if old not in text:
        raise ValueError((name, old))
    count = text.count(old)
    path.write_text(text.replace(old, new), encoding='utf-8', newline='\n')
    changes.append({'archivo': name, 'antes': old, 'despues': new, 'ocurrencias': count})

paragraph('descripcion.tex', 'Ahora bien, desde la perspectiva', r'''Desde la perspectiva de la analítica de aprendizaje y la minería de datos educativos, el comportamiento en un LMS se describe mediante patrones observables de interacción: cómo, cuándo, cuánto y con qué continuidad participa un estudiante. Estos patrones permiten construir indicadores a partir de los registros de la plataforma, sin asumir que midan directamente la motivación o la intención de abandonar \cite{sdata2017171,0007767901540164,bonviewJDSIS42023777}. La baja interacción requiere examinarse dentro de una trayectoria temporal, porque su relación con el riesgo puede variar según la participación previa \cite{1049482020222124425,arXiv260408870}. Por ello, el problema consiste en representar las señales académicas, conductuales y temporales que pueden ayudar a identificar riesgo temprano \cite{bdcc9110297,03064190261439624}.''')
paragraph('descripcion.tex', 'La denominación varía', r'''La literatura utiliza distintas denominaciones para estas plataformas. En sentido estricto, un LMS gestiona el aprendizaje de una organización, mientras un sistema de gestión de cursos se concentra en el curso. Sin embargo, ambos nombres suelen usarse de manera intercambiable \cite{watson2007}. En la tradición británica también se utiliza entorno virtual de aprendizaje (VLE, \textit{Virtual Learning Environment}). La Open University emplea esa denominación para su plataforma y OULAD la conserva en los nombres de sus tablas \cite{sdata2017171}.''')
phrase('descripcion.tex', 'Esta condición se ve radicalizada en el caso de la educación a distancia y en línea, pues', 'En la educación a distancia y en línea,')
phrase('descripcion.tex', 'Para alcanzar este objetivo, la literatura lo organiza', 'La literatura distingue el abandono')
paragraph('descripcion.tex', 'El dato que sostiene', r'''La huella de interacción o \textit{clickstream} reúne acciones digitales con una referencia temporal. En un LMS puede incluir accesos, aperturas de recursos, reproducciones de material, publicaciones en foros, intentos de cuestionario y envíos de evaluaciones, asociados a un estudiante, un recurso y un momento. Estos eventos acompañan el proceso educativo, pero no miden directamente el aprendizaje \cite{03064190261439624,educsci11090552}. La literatura suele relacionarlos con el compromiso estudiantil o \textit{engagement}, que comprende tres dimensiones \cite{fredricks2004}:''')
phrase('descripcion.tex', 'Es habitual acortar la ventana de observación en busca de una predicción lo más temprana posible; sin embargo, esa anticipación se paga en señal disponible, pues un estudiante que apenas ha comenzado a interactuar deja pocos rastros medibles. Por eso, el balance entre anticipación y capacidad discriminante debe evaluarse probando varias ventanas, en lugar de fijar una arbitrariamente.', 'Una ventana corta permite predecir antes, pero reúne menos información: al comienzo del curso puede haber pocos registros de participación. Por ello, la comparación de varias ventanas debe examinar conjuntamente la anticipación disponible y la capacidad para distinguir inscripciones con y sin retiro futuro.')
paragraph('descripcion.tex', 'Es importante tener presente', r'''La huella de interacción tiene dos límites para la predicción temprana. El primero es su comparabilidad entre cursos: un mismo volumen de actividad puede tener significados distintos según el uso educativo de la plataforma \cite{gasevic2016}. OULAD reúne módulos de áreas y duraciones diferentes; por ello, la generalización entre ellos deberá comprobarse durante la evaluación. El segundo límite es temporal. Cada predictor debe utilizar información disponible al momento de emitir la predicción. Incorporar registros posteriores produce fuga de información: el modelo aprovecha datos que no tendría al utilizarse y puede mostrar un desempeño demasiado favorable \cite{kaufman2012,gardnerbrooks2018}.''')
phrase('descripcion.tex', 'Se incluyen así un modelo lineal generalizado, un ensamble por \\textit{bagging}, dos implementaciones de \\textit{gradient boosting} sobre árboles y una arquitectura profunda diseñada para datos tabulares.', 'Se incluyen un modelo lineal generalizado, un ensamble que combina árboles ajustados sobre muestras aleatorias (\\textit{bagging}), dos métodos que añaden árboles para corregir errores sucesivos (\\textit{gradient boosting}) y una red neuronal para datos tabulares, organizados en filas y columnas.')
phrase('descripcion.tex', 'La regresión logística modela la probabilidad de la clase positiva mediante la función logística aplicada a una combinación lineal de los predictores,', 'La regresión logística permite estimar la probabilidad de retiro futuro a partir de los predictores. Para ello, transforma una combinación lineal de sus valores mediante la función logística, que produce un resultado entre cero y uno:')
phrase('descripcion.tex', 'y la inversión de esa expresión revela la escala en que el modelo es lineal, que es también el fundamento de su interpretabilidad:', 'Aquí $\\eta$ es la combinación lineal, $\\beta_0$ es el intercepto y $\\beta_j$ pondera el predictor $x_j$. Para interpretar esos coeficientes se utiliza el \\textit{logit}, es decir, el logaritmo de la razón entre la probabilidad del evento y la de su ausencia:')
phrase('descripcion.tex', 'Random Forest ajusta $B$ árboles de decisión sobre muestras \\textit{bootstrap} del conjunto de entrenamiento y promedia sus estimaciones,', 'Random Forest combina árboles de decisión para estimar la probabilidad de retiro. Cada uno se ajusta sobre una muestra \\textit{bootstrap}, obtenida al seleccionar filas del entrenamiento con reposición. Con $B$ árboles y $\\hat p^{(b)}(\\mathbf x)$ como la probabilidad estimada por el árbol $b$, el resultado es su promedio:')
paragraph('descripcion.tex', 'El promedio puede reducir', r'''Promediar árboles puede reducir la variación de las predicciones, pero el beneficio depende de cuánto se parezcan sus errores. Esta relación se expresa mediante la covarianza, que describe cómo varían conjuntamente. Añadir árboles no garantiza una mejora de todas las métricas, porque el error también depende del sesgo y del problema evaluado. El Anexo~\ref{editorial:rf} conserva la expresión matemática, sus supuestos y la demostración \cite{breiman2001}.''')
paragraph('descripcion.tex', 'La idea es que promediar', '')
paragraph('descripcion.tex', 'Para clasificación logística', r'''XGBoost construye árboles sucesivos para reducir el error del ensamble. En clasificación logística, $z_i$ es la puntuación de la inscripción $i$ antes de transformarla en probabilidad y $\pi_i=\sigma_{\mathrm{log}}(z_i)$ es esa probabilidad. Cada actualización se expresa como $z_i^{(t_{\mathrm{boost}})}=z_i^{(t_{\mathrm{boost}}-1)}+\nu f_{t_{\mathrm{boost}}}(\mathbf{x}_{i})$: el árbol $f_{t_{\mathrm{boost}}}$ se añade a la puntuación anterior y la tasa de aprendizaje $\nu$ regula su aporte. El índice $t_{\mathrm{boost}}$ cuenta iteraciones, no días del curso. Cada árbol se ajusta a partir de la dirección de descenso de la pérdida, que mide el error de las predicciones acumuladas \cite{friedman2001}. Para derivar el ajuste se considera primero el árbol sin reducir su aporte ($\nu=1$); la tasa se aplica después al incorporarlo. El objetivo regularizado es''')
phrase('descripcion.tex', 'Aquí $T$ es el número de hojas, $\\mathbf w$ reúne sus pesos y $t_{\\mathrm{boost}}$ identifica la iteración, no el día de predicción.', 'Aquí $l$ es la pérdida individual, $\\mathcal L$ combina las pérdidas con la penalización $\\Omega$, $T$ cuenta las hojas y $\\mathbf w$ reúne sus pesos. Los coeficientes $\\gamma_{\\mathrm{XGB}}$ y $\\lambda_{\\mathrm{XGB}}$ penalizan el número de hojas y la magnitud de sus pesos, respectivamente.')
paragraph('descripcion.tex', 'La regularización controla aspectos', r'''La regularización limita tanto los pesos como el número de hojas. En la solución del Anexo~\ref{editorial:xgb}, $\lambda_{\mathrm{XGB}}$ aparece en el denominador del peso: al aumentarlo, ese peso se reduce en magnitud, especialmente cuando la suma de segundas derivadas de la pérdida es pequeña. Por su parte, $\gamma_{\mathrm{XGB}}$ exige que la mejora de una división compense el coste de añadir una hoja. Así se puede descartar una división que reduzca poco el error.''')
phrase('descripcion.tex', 'El tratamiento del desbalance se integra en la misma formulación al ponderar $g_{i}$ y $h_{i}$ de la clase minoritaria por un factor constante.', 'El desbalance puede tratarse ponderando por un factor constante las primeras y segundas derivadas de la pérdida, $g_i$ y $h_i$, para los casos de la clase minoritaria. Estas cantidades se definen en el Anexo~\\ref{editorial:xgb}; la ponderación concreta deberá fijarse en el entrenamiento.')
paragraph('descripcion.tex', 'La selección de variables es por tanto', r'''La selección mediante máscaras depende de cada observación. Al reunirlas a lo largo de los pasos se obtiene una importancia por caso, distinta de la selección global de variables antes del entrenamiento y de las atribuciones \textit{post-hoc}. Las comparaciones sobre conjuntos tabulares muestran que los ensambles de árboles siguen siendo competitivos o superiores y que las redes profundas pueden requerir mayor esfuerzo de ajuste \cite{shwartzziv2022,grinsztajn2022}. Por ello, el desempeño de TabNet deberá evaluarse en OULAD. El proyecto lo incorpora como candidato con reglas comunes de comparación; junto con la regresión logística, ofrece una interpretación basada en su propia estructura. La Tabla~\ref{tab:modelos-candidatos} resume los cinco candidatos.''')
phrase('descripcion.tex', 'mediante las curvas ROC y de precisión y exhaustividad, junto con métricas calculadas para el umbral elegido', 'mediante las curvas ROC, que relacionan la proporción de retiros detectados con la proporción de falsas alertas, y las curvas de precisión y exhaustividad, que relacionan la proporción de alertas correctas con la proporción de retiros detectados. También se utilizarán métricas para el umbral elegido')
phrase('descripcion.tex', 'CRISP-DM ofrece una forma', 'CRISP-DM (\\textit{Cross-Industry Standard Process for Data Mining}) ofrece una forma')
paragraph('descripcion.tex', 'La interpretabilidad no constituye', r'''La interpretabilidad busca que una explicación sea comprensible para su destinatario y responda a una pregunta concreta; por ello, su definición y evaluación dependen del contexto \cite{doshivelez2017}. Se distinguen los modelos cuya estructura permite una lectura directa y las técnicas \textit{post-hoc}, aplicadas después del entrenamiento. También se distingue la explicación global, que resume el comportamiento del modelo sobre un conjunto de casos, de la local, que examina una predicción particular \cite{03064190261439624,bdcc9110297}. En este proyecto, la lectura global permitirá reconocer qué variables utiliza el modelo y la local examinará su predicción para una inscripción. Ambas forman parte del análisis previsto; no constituyen una intervención educativa evaluada.''')
paragraph('descripcion.tex', 'La pertinencia de las técnicas', r'''Las explicaciones \textit{post-hoc} requieren cautela: una aproximación que representa bien el comportamiento promedio del modelo puede resultar poco fiel en casos particulares. Por ello, se ha recomendado utilizar modelos de lectura directa cuando las decisiones afectan a personas y su desempeño resulta comparable \cite{rudin2019}. El proyecto conserva dos condiciones para la comparación: incluir un modelo base interpretable, de modo que la diferencia de desempeño pueda medirse, y presentar las explicaciones como atribuciones del modelo. Estas atribuciones no identifican causas del abandono.''')
phrase('descripcion.tex', 'SHAP permite descomponer', 'SHAP (\\textit{SHapley Additive exPlanations}) permite descomponer')
phrase('descripcion.tex', 'La explicación parte de un valor de referencia, que bajo la formulación habitual es', 'En la identidad, $f(\\mathbf x)$ es la salida explicada para la inscripción, $\\phi_0$ es el valor de referencia y $\\phi_j$ es la contribución de la variable $j$, entre las $p$ variables. El conjunto vacío $\\varnothing$ representa la referencia sin variables presentes en la explicación. Bajo la formulación habitual, ese valor es')
paragraph('descripcion.tex', 'Las atribuciones locales pueden', r'''Para resumir la importancia de una variable en un conjunto de casos se promedian las magnitudes de sus contribuciones: $I_{\mathrm{SHAP},j}=n^{-1}\sum_{i=1}^{n}\big|\phi_{j}^{(i)}\big|$. Aquí $n$ es el número de casos explicados y $\phi_j^{(i)}$ la atribución de la variable $j$ al caso $i$. El valor absoluto evita que contribuciones positivas y negativas se cancelen; por ello, esta medida resume magnitud, no dirección. Las atribuciones también permiten examinar interacciones y curvas de dependencia. Su agregación vincula la lectura local y la global mediante un mismo procedimiento, pero no certifica ausencia de sesgo ni resuelve automáticamente la dependencia entre predictores.''')

phrase('abstract.tex', 'El entrenamiento, la interpretación mediante SHAP', 'El entrenamiento, la interpretación mediante SHAP (atribuciones de las variables a las predicciones del modelo)')
phrase('introduccion.tex', 'utiliza OULAD, un conjunto de datos', 'utiliza OULAD (\\textit{Open University Learning Analytics Dataset}), un conjunto de datos')
phrase('desarrollo1.tex', 'La dependencia entre variabilidad y frecuencia impide presentar estas asociaciones como evidencia independiente. Sin embargo, las magnitudes cambian al variar simultáneamente la historia observada, la población y el horizonte;', 'La variabilidad y la frecuencia están relacionadas por sus propias definiciones; por ello, estas asociaciones no representan aportes independientes. Además, las magnitudes cambian al variar simultáneamente la historia observada, la población y el horizonte;')
phrase('desarrollo1.tex', 'La comparación de proporciones y recencias relativas reduce la dependencia aritmética de la duración observada, pero no iguala las oportunidades educativas.', 'Dividir la actividad y la recencia por los días observados facilita comparar ventanas de distinta duración. Sin embargo, esta operación no iguala las oportunidades de participación y evaluación de los cursos.')
phrase('desarrollo1.tex', 'Categoría de privación socioeconómica del área de residencia (IMD)', 'Categoría del índice de privación múltiple del área de residencia (IMD)')
phrase('desarrollo1.tex', 'La categoría IMD corresponde al área de residencia', 'El índice de privación múltiple (IMD, \\textit{Index of Multiple Deprivation}) corresponde al área de residencia')

phrase('desarrollo2.tex', 'Ningún CV se presenta como evidencia independiente de la frecuencia por el solo hecho de tener otro nombre.', 'Por tanto, cambiar el nombre o la definición del CV no demuestra que aporte información independiente de la frecuencia de actividad.')
phrase('desarrollo2.tex', 'quedan 2\\,643 retiros preinicio', 'quedan 2\\,643 retiros anteriores al inicio')
phrase('desarrollo2.tex', 'El sumando 1 de la tendencia permite cocientes finitos con un bloque nulo. Se trata de un suavizado: intercambiar los bloques invierte exactamente el signo, pero escalar los conteos no conserva necesariamente el valor.', 'En la fórmula, $s$ es la duración de cada bloque y $T_{i,s}(t)$ es la tendencia de la inscripción $i$. El numerador suma los clics del bloque más reciente y el denominador los del anterior. Un valor positivo indica más clics recientes y uno negativo, menos. Añadir 1 permite calcular el cociente cuando uno de los bloques no tiene clics. Este suavizado conserva la inversión del signo al intercambiar los bloques, pero multiplicar todos los conteos por una misma cantidad puede cambiar el valor.')
phrase('desarrollo2.tex', 'Ninguna de estas banderas sustituye', 'Ninguno de estos indicadores binarios, con valores 0 o 1, sustituye')
phrase('desarrollo2.tex', 'El primer vencimiento continuo varía', 'El primer vencimiento de evaluación continua varía')
phrase('desarrollo2.tex', 'Primer vencimiento no Exam por módulo y presentación.', 'Primer vencimiento de una evaluación distinta de examen (\\textit{Exam}), por módulo y presentación.')
phrase('desarrollo2.tex', 'Observabilidad de cada indicador; porcentaje', 'Disponibilidad de cada indicador para su cálculo; porcentaje')
phrase('desarrollo2.tex', 'Se calcularon correlaciones de Spearman y se contó cuántos pares de datos estaban disponibles en cada corte.', 'Se calcularon correlaciones de Spearman, que comparan el orden de los valores de dos indicadores. Un signo positivo indica que valores mayores de uno tienden a acompañarse de valores mayores del otro; un signo negativo indica el orden contrario. Se contó cuántos pares de datos estaban disponibles en cada corte.')
phrase('desarrollo2.tex', 'Sus valores describen la dependencia lineal de ese conjunto, pero no determinan qué variables serán más útiles para predecir el retiro.', 'El VIF indica cuánto aumenta la varianza de un coeficiente lineal por su relación con los demás predictores del conjunto. Un valor mayor señala más redundancia lineal, pero no determina qué variables serán más útiles para predecir el retiro.')
phrase('desarrollo2.tex', 'Las variables se estandarizan para llevarlas a una escala comparable', 'Las variables se estandarizan restando su media y dividiendo por su desviación estándar, para llevarlas a una escala comparable')
phrase('desarrollo2.tex', 'Por ello, los componentes de un corte', 'Cada componente es una combinación lineal de los indicadores que resume parte de su variación conjunta. El porcentaje de varianza de la Tabla~\\ref{multi03:pca} expresa cuánto de esa variación recogen los dos primeros componentes. Por ello, los componentes de un corte')
phrase('desarrollo2.tex', 'También se utilizó MCD para revisar', 'También se utilizó el método de determinante mínimo de covarianza (MCD) para revisar')
phrase('desarrollo2.tex', 'Cambio del efecto biserial al retirar exactos:', 'Cambio del efecto biserial al retirar duplicados exactos:')
phrase('desarrollo2.tex', 'El signo corresponde a alternativa menos fuente original;', 'La diferencia se calcula restando el efecto de la fuente original al de la alternativa sin duplicados exactos;')

paragraph('desarrollo3.tex', 'El entrenamiento y la comparación', r'''El entrenamiento y la comparación de clasificadores no se han ejecutado en esta versión. Esta fase deberá establecer qué casos nuevos se espera predecir y cómo separar los datos para evaluarlos, teniendo en cuenta las personas con varias inscripciones y las distintas presentaciones. También deberá incluir modelos base y reglas comunes de comparación.

Las transformaciones, la selección de variables, los hiperparámetros y los umbrales se ajustarán con entrenamiento y validación. La evaluación deberá comprobar la calibración, es decir, la correspondencia entre las probabilidades estimadas y los retiros observados, y el tiempo disponible entre la predicción y el evento. Como ya se exploró la fuente completa, no puede afirmarse que una prueba final permanezca intacta sin evidencia adicional.''')
paragraph('desarrollo4.tex', 'El análisis SHAP permanece', r'''El análisis SHAP requiere un modelo ajustado y evaluado; por ello, permanece pendiente. Su propósito será explicar cómo intervienen las variables en las predicciones. Al ejecutarlo deberán documentarse la variante utilizada, los datos de referencia, la escala de la salida explicada y el tratamiento de predictores relacionados entre sí. Las atribuciones describirán el comportamiento del modelo, sin interpretarse como efectos causales sobre la permanencia estudiantil.''')
phrase('Conclusiones.tex', 'utilizar otro CV o variar los indicadores del PCA.', 'utilizar otra definición del coeficiente de variación (CV) o variar los indicadores del análisis de componentes principales (PCA).')

paragraph('anexos.tex', 'Se contrastaron clics', r'''Se contrastaron los clics, los días activos y el CV entre días activos sobre toda la fuente, para las inscripciones elegibles de los cinco cortes. También se comprobaron los límites de fechas, los indicadores candidatos y las etiquetas, así como que añadir información futura no modificara los predictores del corte. La alternativa sin duplicados exactos conserva la población y el evento. Los intervalos utilizan 5\,000 remuestreos de personas; su estabilidad numérica se examina comparando las primeras 500 y 2\,000 repeticiones con la secuencia completa. Esta comprobación no demuestra una convergencia universal.''')
phrase('anexos.tex', 'Los registros independientes y los hashes identifican la ejecución y los artefactos.', 'Los registros independientes y las huellas digitales de los archivos permiten identificar la ejecución documentada y sus productos.')
phrase('anexos.tex', 'Cada celda informa retiros futuros sobre inscripciones elegibles y el porcentaje correspondiente.', 'Cada celda presenta el número de retiros futuros, el total de inscripciones elegibles de esa categoría y el porcentaje obtenido al dividir ambos conteos. Las columnas corresponden a días de corte; sus poblaciones y periodos de seguimiento pueden variar.')
phrase('anexos.tex', 'Se documentan 26 candidatos, incluidos ambos CV;', 'El diccionario permite relacionar los indicadores del texto con los nombres utilizados en el código. Se documentan 26 candidatos, incluidos ambos CV;')
phrase('anexos.tex', 'Los identificadores, el contexto y los desenlaces permanecen separados.', 'Los identificadores, las variables de contexto y los desenlaces permanecen separados. En la tabla, $t$ es el día de corte; los intervalos de días incluyen ambos extremos. NaN identifica un valor que no puede calcularse con la información disponible, no un cero; SD significa desviación estándar. La función \\texttt{floor} toma la parte entera inferior y permite contar semanas completas.')
phrase('anexos.tex', 'Estas derivaciones amplían las formulaciones del marco teórico; su traslado conserva las hipótesis y los resultados.', 'Estas derivaciones explican la relación entre las formulaciones del marco teórico y sus condiciones matemáticas. Se conserva el detalle para consultar cómo se obtienen los resultados y bajo qué hipótesis son válidos.')
phrase('anexos.tex', '\\subsection{Varianza del promedio en Random Forest}\\label{editorial:rf}', '\\subsection{Varianza del promedio en Random Forest}\\label{editorial:rf}\nLa proposición permite examinar por qué promediar árboles puede reducir la variación de las predicciones. Cada $T_b$ representa un estimador, $B$ cuenta los árboles, $\\sigma_{\\mathrm{RF}}^2$ es su varianza común y $\\rho_{\\mathrm{RF}}$ su correlación común por pares. Se trata de un caso idealizado que explicita las condiciones del resultado.')
phrase('anexos.tex', 'El objetivo aproximado tiene, fijada la estructura del árbol, una solución en forma cerrada.', 'Una vez fijadas las divisiones del árbol, se busca el peso que minimiza el objetivo de cada hoja. La siguiente proposición expresa ese peso mediante las sumas de derivadas y calcula cuánto mejora el objetivo al dividir una hoja en dos.')
phrase('anexos.tex', '\\subsection{Condiciones de unicidad de la atribución SHAP}\\label{editorial:shap}', '\\subsection{Condiciones de unicidad de la atribución SHAP}\\label{editorial:shap}\nEste resultado delimita cuándo las contribuciones de las variables quedan determinadas por las propiedades de la explicación. Una coalición es un conjunto de variables consideradas presentes; su función de valor establece la salida que se les asigna. La unicidad solo se afirma después de fijar esas elecciones.')
phrase('anexos.tex', 'Los parámetros se estiman por máxima verosimilitud, mediante la maximización de', 'El ajuste busca parámetros que asignen mayor probabilidad a las etiquetas observadas en el entrenamiento. La máxima verosimilitud lo expresa mediante la maximización de')
phrase('anexos.tex', 'problema que carece de solución cerrada y se resuelve por métodos iterativos de segundo orden, habitualmente Newton-Raphson en su forma de mínimos cuadrados ponderados iterativamente \\cite{hosmer2013,james2023}.', 'Aquí $\\ell$ es la log-verosimilitud, $y_i$ la etiqueta y $\\pi_i$ la probabilidad estimada para la inscripción $i$; $n$ cuenta las inscripciones del entrenamiento. Cada término recompensa asignar una probabilidad alta a la clase observada. La solución no se obtiene mediante una fórmula cerrada: se aproxima actualizando los coeficientes de forma iterativa, habitualmente con Newton--Raphson expresado como mínimos cuadrados ponderados iterativamente \\cite{hosmer2013,james2023}.')
phrase('anexos.tex', 'Se asume $\\lambda_{\\mathrm{LR}}\\geq0$ y $0\\leq\\alpha\\leq1$.', 'Se asume $\\lambda_{\\mathrm{LR}}\\geq0$ y $0\\leq\\alpha\\leq1$. El primero regula la intensidad de la penalización y el segundo combina la suma de cuadrados ($\\ell_2$) con la suma de valores absolutos ($\\ell_1$). Así, el objetivo equilibra el ajuste a las etiquetas y la magnitud de los coeficientes.')
phrase('anexos.tex', 'El procedimiento GOSS conserva', 'El muestreo unilateral basado en gradientes (GOSS) busca reducir los casos utilizados sin perder la contribución de los que presentan mayores gradientes. El procedimiento conserva')
phrase('anexos.tex', 'La agrupación EFB combina características suficientemente excluyentes para reducir el trabajo sobre matrices dispersas.', 'La agrupación de características excluyentes (EFB) combina variables que rara vez toman valores distintos de cero simultáneamente. Su propósito es reducir el trabajo sobre matrices dispersas, en las que predominan los ceros.')
phrase('anexos.tex', 'La dispersión de las máscaras se induce además mediante un término de entropía añadido a la pérdida,', 'Para favorecer máscaras que concentren el peso en pocas variables, se añade a la pérdida un término de entropía. La entropía mide cómo se reparte el peso entre las componentes de la máscara:')
phrase('anexos.tex', 'con $N_{b}$ el tamaño del lote, ponderado por un coeficiente $\\lambda_{\\text{disp}}$ que, junto con el número de pasos y la dimensión de las representaciones internas, constituye el conjunto de hiperparámetros propios de la arquitectura.', 'Aquí $N_b$ es el número de casos del lote, $N_s$ el número de pasos y $\\mathbf M_{b,j}[s_{\\mathrm{TN}}]$ el peso de la variable $j$ para el caso $b$ en ese paso. El valor positivo $\\epsilon$ estabiliza el logaritmo. El término se pondera con $\\lambda_{\\text{disp}}$; ese peso, el número de pasos y la dimensión de las representaciones internas son hiperparámetros que deberán ajustarse durante el entrenamiento.')
phrase('anexos.tex', 'donde $h_{s_{\\mathrm{TN}}}$ es una transformación entrenable', 'En estas expresiones, $\\mathbf a$ es el estado interno, $\\mathbf M$ la máscara y $\\mathbf P$ el factor que regula el uso previo de variables. El operador $\\odot$ multiplica las componentes correspondientes y $\\prod$ acumula esos factores entre pasos. La función $h_{s_{\\mathrm{TN}}}$ es una transformación entrenable')
phrase('anexos.tex', 'donde $v_x(S)$, abreviado como $v(S)$, es el valor asignado a la coalición $S$ para la observación $x$.', 'Aquí $S$ recorre los subconjuntos de variables que no incluyen a $j$, y $v_x(S)$, abreviado como $v(S)$, es el valor asignado a cada conjunto para la observación $x$. La diferencia entre corchetes mide cuánto cambia ese valor al incorporar $j$. El símbolo $|S|$ cuenta sus variables y $!$ denota el factorial utilizado en la ponderación.')
phrase('anexos.tex', 'Una elección condicional es $\\mathbb{E}[f(X)\\mid X_S=x_S]$; otra integra $f(x_S,X_{-S})$ sobre una distribución de referencia.', 'Una elección condicional es $\\mathbb{E}[f(X)\\mid X_S=x_S]$: promedia la salida del modelo condicionada a los valores observados de las variables de $S$. Otra integra $f(x_S,X_{-S})$ sobre una distribución de referencia, fijando esas variables y variando las restantes. $X_S$ es el subvector de variables de $S$, $x_S$ sus valores observados y $X_{-S}$ las variables complementarias.')

phrase('figura_indicadores.tex', 'Se preservan claves y faltantes estructurales.', 'Se conservan las claves y los indicadores que no pueden calcularse.')
phrase('notacion.tex', '$F;\\ S;\\ j;\\ p$ & Conjunto de características, coalición, característica explicada', '$F;\\ S;\\ j;\\ p$ & Conjunto de características, subconjunto o coalición, característica explicada')

OUT.mkdir(parents=True, exist_ok=True)
(OUT/'cambios.json').write_text(json.dumps(changes, ensure_ascii=False, indent=2), encoding='utf-8')
print(f'{len(changes)} cambios localizados; registro: {OUT}')
